/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csse.exam.main;

import java.awt.Color;
/**
 *
 * @author user
 */
public class ExamDetails extends javax.swing.JFrame {

    /**
     * Creates new form ExamDetails
     */
    public ExamDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlCourse = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        pnlExam = new javax.swing.JPanel();
        lblExam = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSystem = new javax.swing.JPanel();
        lblSystem = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlExamDetails = new javax.swing.JPanel();
        lblExamType = new javax.swing.JLabel();
        lblExamId = new javax.swing.JLabel();
        lblModuleId = new javax.swing.JLabel();
        lblExamDate = new javax.swing.JLabel();
        lblExamDuration = new javax.swing.JLabel();
        lblQuestionNo = new javax.swing.JLabel();
        lblAllocatedMarks = new javax.swing.JLabel();
        cmbExamType = new javax.swing.JComboBox<>();
        txtMarks = new javax.swing.JTextField();
        txtExamCode = new javax.swing.JTextField();
        txtModuleId = new javax.swing.JTextField();
        txtDurationValue = new javax.swing.JTextField();
        txtQuestionNo = new javax.swing.JTextField();
        cmbDurationUnit = new javax.swing.JComboBox<>();
        datePickerExamDate = new com.toedter.calendar.JDateChooser();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlExamDetailTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExamDetails = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavigation.setBackground(new java.awt.Color(105, 135, 170));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboard.setBackground(new java.awt.Color(70, 102, 144));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseReleased(evt);
            }
        });

        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 50));

        pnlCourse.setBackground(new java.awt.Color(70, 102, 144));
        pnlCourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCourseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlCourseMouseReleased(evt);
            }
        });

        lblCourse.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setText("Course");
        lblCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlCourseLayout = new javax.swing.GroupLayout(pnlCourse);
        pnlCourse.setLayout(pnlCourseLayout);
        pnlCourseLayout.setHorizontalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCourseLayout.setVerticalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 50));

        pnlExam.setBackground(new java.awt.Color(70, 102, 144));
        pnlExam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamMouseReleased(evt);
            }
        });

        lblExam.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblExam.setForeground(new java.awt.Color(255, 255, 255));
        lblExam.setText("Exam");

        javax.swing.GroupLayout pnlExamLayout = new javax.swing.GroupLayout(pnlExam);
        pnlExam.setLayout(pnlExamLayout);
        pnlExamLayout.setHorizontalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamLayout.setVerticalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 50));

        pnlResult.setBackground(new java.awt.Color(70, 102, 144));
        pnlResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlResultMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlResultMouseReleased(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 50));

        pnlLogo.setBackground(new java.awt.Color(204, 217, 233));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csse/exam/resource/SLIIT_Crest.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        getContentPane().add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 620));

        pnlSystem.setBackground(new java.awt.Color(105, 135, 170));
        pnlSystem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystem.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("MCQ EXAM SYSTEM");
        pnlSystem.add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("BobTheBuilder");
        lblUser.setToolTipText("");
        pnlSystem.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 10, 460, 20));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 217, 233));
        lblLogout.setText("(LOGOUT)");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSystem.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 20));

        pnlTitle.setBackground(new java.awt.Color(70, 102, 144));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Examination Details");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSystem.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 40));

        getContentPane().add(pnlSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 830, 100));

        pnlContent.setBackground(new java.awt.Color(204, 217, 233));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExamDetails.setBackground(new java.awt.Color(204, 217, 233));
        pnlExamDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExamType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamType.setText("EXAMINATION TYPE :");
        pnlExamDetails.add(lblExamType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        lblExamId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamId.setText("EXAMINATION CODE :");
        pnlExamDetails.add(lblExamId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 40));

        lblModuleId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModuleId.setText("MODULE ID :");
        pnlExamDetails.add(lblModuleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 40));

        lblExamDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamDate.setText("EXAM DATE :");
        pnlExamDetails.add(lblExamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 40));

        lblExamDuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamDuration.setText("DURATION :");
        pnlExamDetails.add(lblExamDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 180, 40));

        lblQuestionNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuestionNo.setText("NO OF QUESTIONS :");
        pnlExamDetails.add(lblQuestionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 180, 40));

        lblAllocatedMarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAllocatedMarks.setText("ALLOCATED MARKS : ");
        pnlExamDetails.add(lblAllocatedMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 180, 40));

        cmbExamType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbExamType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT EXAM TYPE", "MID EXAM", "ASSIGNMENT", "FINAL EXAM" }));
        pnlExamDetails.add(cmbExamType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, 30));
        pnlExamDetails.add(txtMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 180, 30));
        pnlExamDetails.add(txtExamCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, 30));
        pnlExamDetails.add(txtModuleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, 30));
        pnlExamDetails.add(txtDurationValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 70, 30));
        pnlExamDetails.add(txtQuestionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 180, 30));

        cmbDurationUnit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDurationUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIME UNIT", "mins", "hrs" }));
        pnlExamDetails.add(cmbDurationUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 30));
        pnlExamDetails.add(datePickerExamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 180, 30));

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("CLEAR");
        pnlExamDetails.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 110, 40));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("ADD");
        pnlExamDetails.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 110, 40));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setToolTipText("");
        pnlExamDetails.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 110, 40));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("DELETE");
        pnlExamDetails.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 110, 40));

        pnlContent.add(pnlExamDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 790, 220));

        pnlExamDetailTable.setBackground(new java.awt.Color(204, 217, 233));
        pnlExamDetailTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamDetailTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblExamDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EXAMINATION CODE", "MODULE ID", "EXAM DATE", "EXAM DURATION", "NO OF QUESTIONS", "ALLOCATED MARKS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExamDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblExamDetails);

        pnlExamDetailTable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 240));

        pnlContent.add(pnlExamDetailTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 790, 260));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 830, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDashboardMouseClicked

    private void pnlDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseEntered
        // TODO add your handling code here:
        //        jPanel5.setBackground(new Color(153,150,255));
    }//GEN-LAST:event_pnlDashboardMouseEntered

    private void pnlDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseExited
        // TODO add your handling code here:[153,204,255]
    }//GEN-LAST:event_pnlDashboardMouseExited

    private void pnlDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMousePressed
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlDashboardMousePressed

    private void pnlDashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseReleased
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlDashboardMouseReleased

    private void pnlCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMousePressed
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlCourseMousePressed

    private void pnlCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMouseReleased
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlCourseMouseReleased

    private void pnlExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMousePressed
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamMousePressed

    private void pnlExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMouseReleased
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamMouseReleased

    private void pnlResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMousePressed
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlResultMousePressed

    private void pnlResultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMouseReleased
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlResultMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDurationUnit;
    private javax.swing.JComboBox<String> cmbExamType;
    private com.toedter.calendar.JDateChooser datePickerExamDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllocatedMarks;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblExam;
    private javax.swing.JLabel lblExamDate;
    private javax.swing.JLabel lblExamDuration;
    private javax.swing.JLabel lblExamId;
    private javax.swing.JLabel lblExamType;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblModuleId;
    private javax.swing.JLabel lblQuestionNo;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlExam;
    private javax.swing.JPanel pnlExamDetailTable;
    private javax.swing.JPanel pnlExamDetails;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTable tblExamDetails;
    private javax.swing.JTextField txtDurationValue;
    private javax.swing.JTextField txtExamCode;
    private javax.swing.JTextField txtMarks;
    private javax.swing.JTextField txtModuleId;
    private javax.swing.JTextField txtQuestionNo;
    // End of variables declaration//GEN-END:variables
}
