/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csse.exam.main;

/**
 *
 * @author user
 */
import com.csse.exam.common.ClearComponents;
import com.csse.exam.common.CommonComponents;
import com.csse.exam.common.Validation;
import com.csse.exam.service.QuestionService;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.Arrays;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JOptionPane;
public class ExamQuestion extends javax.swing.JFrame {

    /**
     * Creates new form ExamQuestion
     */
    private final CommonComponents commonComponents = new CommonComponents();
    private final QuestionService questionService = new QuestionService();
    private final Validation validation = new Validation();
    private final ClearComponents clear = new ClearComponents();
    
    String examType;
    String examId;
    String moduleId;
    String examDate;
    String examTime;
    String examTimeUnit;
    String questionNo;
    String allocatedMarks;
    String examDuration;
    String questionId;
    String question;
    String options;
    String option1;
    String option2;
    String option3;
    String option4;
    String option5;
    
    
    public ExamQuestion() {
        initComponents();
        commonComponents.addValueToComboBox(cmbExamId, "exam", "examId");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlCourse = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        pnlExam = new javax.swing.JPanel();
        lblExam = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblSystem = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlExamDetails = new javax.swing.JPanel();
        lblExamCode = new javax.swing.JLabel();
        lblExamType = new javax.swing.JLabel();
        lblExamDate = new javax.swing.JLabel();
        lblQuestionsCount = new javax.swing.JLabel();
        lblAllocatedMarks = new javax.swing.JLabel();
        cmbExamId = new javax.swing.JComboBox<>();
        lblExamDuration = new javax.swing.JLabel();
        txtExamDate = new javax.swing.JTextField();
        txtTotalQuestions = new javax.swing.JTextField();
        txtExamType = new javax.swing.JTextField();
        txtExamDuration = new javax.swing.JTextField();
        txtAllocatedMarks = new javax.swing.JTextField();
        pnlQuestionBank = new javax.swing.JPanel();
        pnlQuestions = new javax.swing.JPanel();
        lblOption5 = new javax.swing.JLabel();
        lblQuestionNumber1 = new javax.swing.JLabel();
        lblQuestionDescription1 = new javax.swing.JLabel();
        lblOption1 = new javax.swing.JLabel();
        lblOption2 = new javax.swing.JLabel();
        lblOption3 = new javax.swing.JLabel();
        lblOption4 = new javax.swing.JLabel();
        txtOption5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaQuestion = new javax.swing.JTextArea();
        txtQuestionId = new javax.swing.JTextField();
        txtOption1 = new javax.swing.JTextField();
        txtOption3 = new javax.swing.JTextField();
        txtOption4 = new javax.swing.JTextField();
        txtOption2 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXAM");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavigation.setBackground(new java.awt.Color(105, 135, 170));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboard.setBackground(new java.awt.Color(70, 102, 144));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseReleased(evt);
            }
        });

        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 50));

        pnlCourse.setBackground(new java.awt.Color(70, 102, 144));
        pnlCourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCourseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlCourseMouseReleased(evt);
            }
        });

        lblCourse.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setText("Course");
        lblCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlCourseLayout = new javax.swing.GroupLayout(pnlCourse);
        pnlCourse.setLayout(pnlCourseLayout);
        pnlCourseLayout.setHorizontalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCourseLayout.setVerticalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 50));

        pnlExam.setBackground(new java.awt.Color(70, 102, 144));
        pnlExam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamMouseReleased(evt);
            }
        });

        lblExam.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblExam.setForeground(new java.awt.Color(255, 255, 255));
        lblExam.setText("Exam");

        javax.swing.GroupLayout pnlExamLayout = new javax.swing.GroupLayout(pnlExam);
        pnlExam.setLayout(pnlExamLayout);
        pnlExamLayout.setHorizontalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamLayout.setVerticalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 50));

        pnlResult.setBackground(new java.awt.Color(70, 102, 144));
        pnlResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlResultMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlResultMouseReleased(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 50));

        pnlLogo.setBackground(new java.awt.Color(204, 217, 233));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csse/exam/resource/SLIIT_Crest.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        getContentPane().add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 620));

        pnlHeader.setBackground(new java.awt.Color(105, 135, 170));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystem.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("MCQ EXAM SYSTEM");
        pnlHeader.add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("BobTheBuilder");
        lblUser.setToolTipText("");
        pnlHeader.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 10, 460, 20));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 217, 233));
        lblLogout.setText("(LOGOUT)");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 20));

        pnlTitle.setBackground(new java.awt.Color(70, 102, 144));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Question Bank");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlHeader.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 40));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 830, 100));

        pnlContent.setBackground(new java.awt.Color(204, 217, 233));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExamDetails.setBackground(new java.awt.Color(204, 217, 233));
        pnlExamDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExamCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamCode.setText("EXAMINATION CODE :");
        pnlExamDetails.add(lblExamCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        lblExamType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamType.setText("EXAMINATION TYPE :");
        pnlExamDetails.add(lblExamType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 30));

        lblExamDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamDate.setText("EXAMINATION DATE :");
        pnlExamDetails.add(lblExamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        lblQuestionsCount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuestionsCount.setText("TOTAL NO OF QUESTIONS :");
        pnlExamDetails.add(lblQuestionsCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 190, 30));

        lblAllocatedMarks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAllocatedMarks.setText("ALLOCATED MARKS :");
        pnlExamDetails.add(lblAllocatedMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, 30));

        cmbExamId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbExamId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT EXAMINATION CODE" }));
        cmbExamId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbExamIdActionPerformed(evt);
            }
        });
        pnlExamDetails.add(cmbExamId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 220, 30));

        lblExamDuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamDuration.setText("EXAMINATION DURATION :");
        pnlExamDetails.add(lblExamDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 30));

        txtExamDate.setEditable(false);
        txtExamDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlExamDetails.add(txtExamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 26));

        txtTotalQuestions.setEditable(false);
        txtTotalQuestions.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlExamDetails.add(txtTotalQuestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 160, 26));

        txtExamType.setEditable(false);
        txtExamType.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlExamDetails.add(txtExamType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 42, 220, 26));

        txtExamDuration.setEditable(false);
        txtExamDuration.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlExamDetails.add(txtExamDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 14, 160, 26));

        txtAllocatedMarks.setEditable(false);
        txtAllocatedMarks.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlExamDetails.add(txtAllocatedMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 42, 160, 26));

        pnlContent.add(pnlExamDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 100));

        pnlQuestionBank.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        pnlQuestionBank.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlQuestionBankLayout = new javax.swing.GroupLayout(pnlQuestionBank);
        pnlQuestionBank.setLayout(pnlQuestionBankLayout);
        pnlQuestionBankLayout.setHorizontalGroup(
            pnlQuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        pnlQuestionBankLayout.setVerticalGroup(
            pnlQuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        pnlContent.add(pnlQuestionBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, 330));

        pnlQuestions.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuestions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOption5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblOption5.setText("OPTION 5 :");
        pnlQuestions.add(lblOption5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 30));

        lblQuestionNumber1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblQuestionNumber1.setText("QUESTION NO :");
        pnlQuestions.add(lblQuestionNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        lblQuestionDescription1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblQuestionDescription1.setText("QUESTION :");
        pnlQuestions.add(lblQuestionDescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        lblOption1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblOption1.setText("OPTION 1 :");
        pnlQuestions.add(lblOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        lblOption2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblOption2.setText("OPTION 2 :");
        pnlQuestions.add(lblOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        lblOption3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblOption3.setText("OPTION 3 :");
        pnlQuestions.add(lblOption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 30));

        lblOption4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblOption4.setText("OPTION 4 :");
        pnlQuestions.add(lblOption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        txtOption5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlQuestions.add(txtOption5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 450, 27));

        txtAreaQuestion.setColumns(20);
        txtAreaQuestion.setRows(5);
        jScrollPane1.setViewportView(txtAreaQuestion);

        pnlQuestions.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 45, 450, 120));

        txtQuestionId.setEditable(false);
        txtQuestionId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlQuestions.add(txtQuestionId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 11, 220, 30));

        txtOption1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlQuestions.add(txtOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 450, 27));

        txtOption3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlQuestions.add(txtOption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 450, 27));

        txtOption4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlQuestions.add(txtOption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 450, 27));

        txtOption2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pnlQuestions.add(txtOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 450, 27));

        pnlContent.add(pnlQuestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 560, 330));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        pnlContent.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 180, 40));

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        pnlContent.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 180, 40));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 830, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDashboardMouseClicked

    private void pnlDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseEntered
        // TODO add your handling code here:
        //        jPanel5.setBackground(new Color(153,150,255));
    }//GEN-LAST:event_pnlDashboardMouseEntered

    private void pnlDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseExited
        // TODO add your handling code here:[153,204,255]
    }//GEN-LAST:event_pnlDashboardMouseExited

    private void pnlDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMousePressed
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlDashboardMousePressed

    private void pnlDashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseReleased
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlDashboardMouseReleased

    private void pnlCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMousePressed
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlCourseMousePressed

    private void pnlCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMouseReleased
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlCourseMouseReleased

    private void pnlExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMousePressed
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamMousePressed

    private void pnlExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMouseReleased
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamMouseReleased

    private void pnlResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMousePressed
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlResultMousePressed

    private void pnlResultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMouseReleased
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlResultMouseReleased

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        clear.resetComboBox(pnlExamDetails);
        txtAreaQuestion.setText(null);
        clear.clearTextFields(pnlQuestions);
        clear.clearTextFields(pnlExamDetails);
    }//GEN-LAST:event_btnClearMouseClicked

    private void cmbExamIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbExamIdActionPerformed
        // TODO add your handling code here:
        examId = cmbExamId.getSelectedItem().toString();
        Object[] object = new Objects[6];
        object = questionService.getExamDetailsById(examId);
      
        examType = object[1].toString().split("-")[1];
        examDate = object[2].toString();
        examDuration = object[3].toString();
        questionNo = object[4].toString();
        allocatedMarks = object[5].toString();
        
        txtExamType.setText(examType);
        txtExamDate.setText(examDate);
        txtExamDuration.setText(examDuration);
        txtTotalQuestions.setText(questionNo);
        txtAllocatedMarks.setText(allocatedMarks);
        
        questionId =  questionService.getQuestionId(examId);
        txtQuestionId.setText(questionId);
        
        String totalNoQues = questionService.getLatestQuestionId(examId);
        int id = parseInt(totalNoQues.split("Q")[1]);
        System.out.println(totalNoQues.split("Q")[1]);
        System.out.println(totalNoQues);
        int row = id/5;
        int remain = id%5;
        System.out.println(row);
        System.out.println(remain);
        int x = 5;
        int y = 5;
        
     System.out.println("start");
     for(int i=0; i<row; i++)
     {                               
        for(int j=0; j<=4; j++)
        {   
            JButton button = new JButton();
            button.setSize(35, 35);
            button.setLocation(x,y);
            button.setText(questionId);  
            
            pnlQuestionBank.add(button);
            button.setVisible(true);
            System.out.println(button.getLocation());
            x=x+40;           
        }
        x = 5;
        y = y+40;
                  
        System.out.println("");       
     }
     
     if(remain!=0)
     {
         System.out.println(Arrays.toString(pnlQuestionBank.getComponents()));
     }
        
    }//GEN-LAST:event_cmbExamIdActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        examId = cmbExamId.getSelectedItem().toString();
        questionId = txtQuestionId.getText();
        question = txtAreaQuestion.getText();
        option1 = txtOption1.getText();
        option2 = txtOption1.getText();
        option3 = txtOption1.getText();
        option4 = txtOption1.getText();
        option5 = txtOption1.getText();
        
        options = "1-"+option1+":"+"2-"+option2+":"+"3-"+option3+":"+"4-"+option4+":"+"5-"+option5+":";
        System.out.println(options);
        
        boolean nullValue = validation.checkEmptyTextBox(pnlQuestions);
        boolean checkBox = validation.checkComboBox(pnlExamDetails);
        System.out.println("yes");
        System.out.println(nullValue);
        
        if(nullValue==false)
        {
            JOptionPane.showMessageDialog(this, "Please fill all the text boxes", "Error Message", 1);
        }
        else
        {
            boolean value = questionService.addQuestion(examId, questionId, question,options);
            if(value)
            {
                JOptionPane.showMessageDialog(this, "Exam question was successfully added", "Success Message", 1);
                
                int x = 15;
                int y = 15;
                System.out.println("start");
                while(true)
                {
                        JButton button = new JButton();
                        button.setSize(35, 35);
                        button.setLocation(x,y);
                        button.setText(questionId);  
            
                            pnlQuestionBank.add(button);
                            //button.setVisible(true);
                            System.out.println(button.getLocation());
                        
                }
     
            }
        }
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cmbExamId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllocatedMarks;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblExam;
    private javax.swing.JLabel lblExamCode;
    private javax.swing.JLabel lblExamDate;
    private javax.swing.JLabel lblExamDuration;
    private javax.swing.JLabel lblExamType;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblOption1;
    private javax.swing.JLabel lblOption2;
    private javax.swing.JLabel lblOption3;
    private javax.swing.JLabel lblOption4;
    private javax.swing.JLabel lblOption5;
    private javax.swing.JLabel lblQuestionDescription1;
    private javax.swing.JLabel lblQuestionNumber1;
    private javax.swing.JLabel lblQuestionsCount;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlExam;
    private javax.swing.JPanel pnlExamDetails;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlQuestionBank;
    private javax.swing.JPanel pnlQuestions;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtAllocatedMarks;
    private javax.swing.JTextArea txtAreaQuestion;
    private javax.swing.JTextField txtExamDate;
    private javax.swing.JTextField txtExamDuration;
    private javax.swing.JTextField txtExamType;
    private javax.swing.JTextField txtOption1;
    private javax.swing.JTextField txtOption2;
    private javax.swing.JTextField txtOption3;
    private javax.swing.JTextField txtOption4;
    private javax.swing.JTextField txtOption5;
    private javax.swing.JTextField txtQuestionId;
    private javax.swing.JTextField txtTotalQuestions;
    // End of variables declaration//GEN-END:variables
}
