/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csse.exam.main;

import com.csse.exam.common.ClearComponents;
import com.csse.exam.common.Validation;
import com.csse.exam.model.Exam;
import com.csse.exam.service.ExamSummaryService;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author munsif
 */
public class ExamSummary extends javax.swing.JFrame {

    ClearComponents clear;
    Validation validate;
    private final ExamSummaryService examSummaryService = new ExamSummaryService();
    private final List<Exam> examsList = examSummaryService.getExamDetails();
    private DefaultTableModel table;
    String examId;
    String moduleId;
    String examDate;
    String resultState;
    String result;

    /**
     * Creates new form ExamSummary
     */
    public ExamSummary() {
        initComponents();
        setExamDetailsTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlCourse = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        pnlExam = new javax.swing.JPanel();
        lblExam = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSystem = new javax.swing.JPanel();
        lblSystem = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlExamLink = new javax.swing.JPanel();
        lblExamCode = new javax.swing.JLabel();
        lblModuleId = new javax.swing.JLabel();
        lblExamDate = new javax.swing.JLabel();
        lblExamCode1 = new javax.swing.JLabel();
        lblExamLink1 = new javax.swing.JLabel();
        lblStudentsCount = new javax.swing.JLabel();
        lblLinkStatus2 = new javax.swing.JLabel();
        lblLinkStatus3 = new javax.swing.JLabel();
        lblTotalDuration = new javax.swing.JLabel();
        lblPassedCount = new javax.swing.JLabel();
        lblDuration3 = new javax.swing.JLabel();
        lblResultState = new javax.swing.JLabel();
        lblDuration5 = new javax.swing.JLabel();
        lblResultState1 = new javax.swing.JLabel();
        pnlExamLinkTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExamSummary = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXAM SUMMARY");
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavigation.setBackground(new java.awt.Color(105, 135, 170));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboard.setBackground(new java.awt.Color(70, 102, 144));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseReleased(evt);
            }
        });

        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 50));

        pnlCourse.setBackground(new java.awt.Color(70, 102, 144));
        pnlCourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCourseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlCourseMouseReleased(evt);
            }
        });

        lblCourse.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setText("Course");
        lblCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlCourseLayout = new javax.swing.GroupLayout(pnlCourse);
        pnlCourse.setLayout(pnlCourseLayout);
        pnlCourseLayout.setHorizontalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCourseLayout.setVerticalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 50));

        pnlExam.setBackground(new java.awt.Color(70, 102, 144));
        pnlExam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamMouseReleased(evt);
            }
        });

        lblExam.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblExam.setForeground(new java.awt.Color(255, 255, 255));
        lblExam.setText("Exam");

        javax.swing.GroupLayout pnlExamLayout = new javax.swing.GroupLayout(pnlExam);
        pnlExam.setLayout(pnlExamLayout);
        pnlExamLayout.setHorizontalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamLayout.setVerticalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 50));

        pnlResult.setBackground(new java.awt.Color(70, 102, 144));
        pnlResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlResultMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlResultMouseReleased(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 50));

        pnlLogo.setBackground(new java.awt.Color(204, 217, 233));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csse/exam/resource/SLIIT_Crest.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        getContentPane().add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 620));

        pnlSystem.setBackground(new java.awt.Color(105, 135, 170));
        pnlSystem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystem.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("MCQ EXAM SYSTEM");
        pnlSystem.add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("BobTheBuilder");
        lblUser.setToolTipText("");
        pnlSystem.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 10, 460, 20));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 217, 233));
        lblLogout.setText("(LOGOUT)");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSystem.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 20));

        jPanel2.setBackground(new java.awt.Color(70, 102, 144));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exam Summary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSystem.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 40));

        getContentPane().add(pnlSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 830, 100));

        pnlContent.setBackground(new java.awt.Color(204, 217, 233));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExamLink.setBackground(new java.awt.Color(204, 217, 233));
        pnlExamLink.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamLink.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExamCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamCode.setText("EXAMINATION CODE :");
        pnlExamLink.add(lblExamCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 30));

        lblModuleId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblModuleId.setText("MODULE ID:");
        pnlExamLink.add(lblModuleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, 30));

        lblExamDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamDate.setText("EXAM DATE: ");
        pnlExamLink.add(lblExamDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, 30));

        lblExamCode1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamCode1.setText("EXAMINATION CODE:");
        pnlExamLink.add(lblExamCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        lblExamLink1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExamLink1.setText("MODULE ID:");
        pnlExamLink.add(lblExamLink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        lblStudentsCount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStudentsCount.setText("TOTAL STUDENTS:");
        pnlExamLink.add(lblStudentsCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 130, 30));

        lblLinkStatus2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLinkStatus2.setText("EXAM DATE: ");
        pnlExamLink.add(lblLinkStatus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        lblLinkStatus3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLinkStatus3.setText("TOTAL DURATION:");
        pnlExamLink.add(lblLinkStatus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        lblTotalDuration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalDuration.setText("TOTAL DURATION:");
        pnlExamLink.add(lblTotalDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 30));

        lblPassedCount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassedCount.setText("PASSED STUDENTS:");
        pnlExamLink.add(lblPassedCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 130, 30));

        lblDuration3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuration3.setText("TOTAL STUDENTS:");
        pnlExamLink.add(lblDuration3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 30));

        lblResultState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultState.setText("RESULT STATE:");
        pnlExamLink.add(lblResultState, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, 30));

        lblDuration5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuration5.setText("PASSED STUDENTS:");
        pnlExamLink.add(lblDuration5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, 30));

        lblResultState1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultState1.setText("RESULT STATE:");
        pnlExamLink.add(lblResultState1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, 30));

        pnlContent.add(pnlExamLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 200));

        pnlExamLinkTable.setBackground(new java.awt.Color(204, 217, 233));
        pnlExamLinkTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamLinkTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblExamSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam Id", "Module Id", "Exam Date", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExamSummary.setToolTipText("");
        tblExamSummary.getTableHeader().setReorderingAllowed(false);
        tblExamSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExamSummaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExamSummary);

        pnlExamLinkTable.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 240));

        pnlContent.add(pnlExamLinkTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 780, 260));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 830, 520));

        setSize(new java.awt.Dimension(966, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDashboardMouseClicked

    private void pnlDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseEntered
        // TODO add your handling code here:
        //        jPanel5.setBackground(new Color(153,150,255));
    }//GEN-LAST:event_pnlDashboardMouseEntered

    private void pnlDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseExited
        // TODO add your handling code here:[153,204,255]
    }//GEN-LAST:event_pnlDashboardMouseExited

    private void pnlDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMousePressed
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlDashboardMousePressed

    private void pnlDashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseReleased
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlDashboardMouseReleased

    private void pnlCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMousePressed
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlCourseMousePressed

    private void pnlCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMouseReleased
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlCourseMouseReleased

    private void pnlExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMousePressed
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamMousePressed

    private void pnlExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMouseReleased
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamMouseReleased

    private void pnlResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMousePressed
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlResultMousePressed

    private void pnlResultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMouseReleased
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlResultMouseReleased

    private void tblExamSummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExamSummaryMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblExamSummary.getSelectedRow();
        TableModel tModel = tblExamSummary.getModel();
        examId = tModel.getValueAt(selectedRow, 0).toString();
        moduleId = tModel.getValueAt(selectedRow, 1).toString();
        examDate = tModel.getValueAt(selectedRow, 2).toString();
        resultState = tModel.getValueAt(selectedRow, 3).toString();

        if (resultState.equals("Enabled")) {
            result = "Result is Out";
        }
        else {
            result = "Result is Pending";
        }

        setExamLinkDetails(examId);

        int studentCountByExamId = examSummaryService.getStudentCountByExamId(examId);
        int passedStudentCountByExamId = examSummaryService.getPassedStudentCountByExamId(examId);
        lblStudentsCount.setText(String.valueOf(studentCountByExamId));
        lblPassedCount.setText(String.valueOf(passedStudentCountByExamId));
        lblExamCode.setText(examId);
        lblModuleId.setText(moduleId);
        lblExamDate.setText(examDate);
        lblResultState.setText(result);
    }//GEN-LAST:event_tblExamSummaryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamSummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDuration3;
    private javax.swing.JLabel lblDuration5;
    private javax.swing.JLabel lblExam;
    private javax.swing.JLabel lblExamCode;
    private javax.swing.JLabel lblExamCode1;
    private javax.swing.JLabel lblExamDate;
    private javax.swing.JLabel lblExamLink1;
    private javax.swing.JLabel lblLinkStatus2;
    private javax.swing.JLabel lblLinkStatus3;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblModuleId;
    private javax.swing.JLabel lblPassedCount;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResultState;
    private javax.swing.JLabel lblResultState1;
    private javax.swing.JLabel lblStudentsCount;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTotalDuration;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlExam;
    private javax.swing.JPanel pnlExamLink;
    private javax.swing.JPanel pnlExamLinkTable;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JTable tblExamSummary;
    // End of variables declaration//GEN-END:variables

    private void setExamDetailsTable() {
        table = examSummaryService.fillExamSummaryTable();
        tblExamSummary.setModel(table);
    }

    public void setExamLinkDetails(String examId) {
        List<Exam> resultLinkList = examSummaryService.getExamDetailsStream(examId);
        resultLinkList.forEach((result) -> {
            lblTotalDuration.setText(result.getExamDuration());
        });
    }
}
