/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csse.exam.main;

import java.awt.Color;

/**
 *
 * @author user
 */
public class LecturerExamDashboard extends javax.swing.JFrame {

    /**
     * Creates new form LecturerExamDashboard
     */
    public LecturerExamDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        pnlExamDetails = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlExamSession = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlAnswerScheme = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlExamLink = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnlQuestionBank = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlResults = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exam Dashboard");
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavigation.setBackground(new java.awt.Color(105, 135, 170));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(70, 102, 144));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel5MouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dashboard");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 50));

        jPanel6.setBackground(new java.awt.Color(70, 102, 144));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 50));

        jPanel7.setBackground(new java.awt.Color(70, 102, 144));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel7MouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("About Us");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 50));

        jPanel8.setBackground(new java.awt.Color(70, 102, 144));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel8MouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact Us");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 50));

        jPanel1.setBackground(new java.awt.Color(204, 217, 233));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csse/exam/resource/SLIIT_Crest.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        getContentPane().add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 620));

        pnlHeader.setBackground(new java.awt.Color(105, 135, 170));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MCQ EXAM SYSTEM");
        pnlHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("BobTheBuilder");
        jLabel3.setToolTipText("");
        pnlHeader.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 10, 460, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 217, 233));
        jLabel4.setText("(LOGOUT)");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 20));

        jPanel2.setBackground(new java.awt.Color(70, 102, 144));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Exam Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlHeader.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 40));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 830, 100));

        pnlContent.setBackground(new java.awt.Color(204, 217, 233));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBack.setToolTipText("Back");
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackMousePressed(evt);
            }
        });
        pnlContent.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, 30));

        pnlExamDetails.setBackground(new java.awt.Color(70, 102, 144));
        pnlExamDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExamDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExamDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExamDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExamDetailsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamDetailsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamDetailsMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Exam Details");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlExamDetailsLayout = new javax.swing.GroupLayout(pnlExamDetails);
        pnlExamDetails.setLayout(pnlExamDetailsLayout);
        pnlExamDetailsLayout.setHorizontalGroup(
            pnlExamDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamDetailsLayout.setVerticalGroup(
            pnlExamDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlExamDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 260, 110));

        pnlExamSession.setBackground(new java.awt.Color(70, 102, 144));
        pnlExamSession.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamSession.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExamSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExamSessionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExamSessionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExamSessionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamSessionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamSessionMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Exam Session");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlExamSessionLayout = new javax.swing.GroupLayout(pnlExamSession);
        pnlExamSession.setLayout(pnlExamSessionLayout);
        pnlExamSessionLayout.setHorizontalGroup(
            pnlExamSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamSessionLayout.setVerticalGroup(
            pnlExamSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamSessionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlExamSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 260, 110));

        pnlAnswerScheme.setBackground(new java.awt.Color(70, 102, 144));
        pnlAnswerScheme.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlAnswerScheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAnswerScheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAnswerSchemeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAnswerSchemeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAnswerSchemeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAnswerSchemeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlAnswerSchemeMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Answer Scheme");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAnswerSchemeLayout = new javax.swing.GroupLayout(pnlAnswerScheme);
        pnlAnswerScheme.setLayout(pnlAnswerSchemeLayout);
        pnlAnswerSchemeLayout.setHorizontalGroup(
            pnlAnswerSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnswerSchemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAnswerSchemeLayout.setVerticalGroup(
            pnlAnswerSchemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnswerSchemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlAnswerScheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 260, 110));

        pnlExamLink.setBackground(new java.awt.Color(70, 102, 144));
        pnlExamLink.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExamLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExamLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExamLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExamLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExamLinkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamLinkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamLinkMouseReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Exam Link");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlExamLinkLayout = new javax.swing.GroupLayout(pnlExamLink);
        pnlExamLink.setLayout(pnlExamLinkLayout);
        pnlExamLinkLayout.setHorizontalGroup(
            pnlExamLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamLinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamLinkLayout.setVerticalGroup(
            pnlExamLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamLinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlExamLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 260, 110));

        pnlQuestionBank.setBackground(new java.awt.Color(70, 102, 144));
        pnlQuestionBank.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlQuestionBank.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlQuestionBank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlQuestionBankMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlQuestionBankMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQuestionBankMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlQuestionBankMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlQuestionBankMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Question Bank");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestionBankLayout = new javax.swing.GroupLayout(pnlQuestionBank);
        pnlQuestionBank.setLayout(pnlQuestionBankLayout);
        pnlQuestionBankLayout.setHorizontalGroup(
            pnlQuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestionBankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlQuestionBankLayout.setVerticalGroup(
            pnlQuestionBankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestionBankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlQuestionBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 260, 110));

        pnlResults.setBackground(new java.awt.Color(70, 102, 144));
        pnlResults.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlResultsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlResultsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlResultsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlResultsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlResultsMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Results");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 260, 110));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 830, 520));

        setSize(new java.awt.Dimension(966, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        //        jPanel5.setBackground(new Color(153,150,255));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:[153,204,255]
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseReleased
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_jPanel5MouseReleased

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_jPanel6MouseReleased

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseReleased
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_jPanel7MouseReleased

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_jPanel8MousePressed

    private void jPanel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseReleased
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_jPanel8MouseReleased

    private void lblBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMousePressed
        // TODO add your handling code here:
        lblBack.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblBackMousePressed

    private void pnlExamDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamDetailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamDetailsMouseClicked

    private void pnlExamDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamDetailsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamDetailsMouseEntered

    private void pnlExamDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamDetailsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamDetailsMouseExited

    private void pnlExamDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamDetailsMousePressed
        // TODO add your handling code here:
        pnlExamDetails.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamDetailsMousePressed

    private void pnlExamDetailsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamDetailsMouseReleased
        // TODO add your handling code here:
        pnlExamDetails.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamDetailsMouseReleased

    private void pnlExamSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamSessionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamSessionMouseClicked

    private void pnlExamSessionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamSessionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamSessionMouseEntered

    private void pnlExamSessionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamSessionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamSessionMouseExited

    private void pnlExamSessionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamSessionMousePressed
        // TODO add your handling code here:
        pnlExamSession.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamSessionMousePressed

    private void pnlExamSessionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamSessionMouseReleased
        // TODO add your handling code here:
        pnlExamSession.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamSessionMouseReleased

    private void pnlAnswerSchemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnswerSchemeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAnswerSchemeMouseClicked

    private void pnlAnswerSchemeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnswerSchemeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAnswerSchemeMouseEntered

    private void pnlAnswerSchemeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnswerSchemeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAnswerSchemeMouseExited

    private void pnlAnswerSchemeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnswerSchemeMousePressed
        // TODO add your handling code here:
        pnlAnswerScheme.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlAnswerSchemeMousePressed

    private void pnlAnswerSchemeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnswerSchemeMouseReleased
        // TODO add your handling code here:
        pnlAnswerScheme.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlAnswerSchemeMouseReleased

    private void pnlExamLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamLinkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamLinkMouseClicked

    private void pnlExamLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamLinkMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamLinkMouseEntered

    private void pnlExamLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamLinkMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExamLinkMouseExited

    private void pnlExamLinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamLinkMousePressed
        // TODO add your handling code here:
        pnlExamLink.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamLinkMousePressed

    private void pnlExamLinkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamLinkMouseReleased
        // TODO add your handling code here:
        pnlExamLink.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamLinkMouseReleased

    private void pnlQuestionBankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuestionBankMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuestionBankMouseClicked

    private void pnlQuestionBankMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuestionBankMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuestionBankMouseEntered

    private void pnlQuestionBankMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuestionBankMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuestionBankMouseExited

    private void pnlQuestionBankMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuestionBankMousePressed
        // TODO add your handling code here:
        pnlQuestionBank.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlQuestionBankMousePressed

    private void pnlQuestionBankMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuestionBankMouseReleased
        // TODO add your handling code here:
        pnlQuestionBank.setBackground(new Color(70, 102, 144));
        
    }//GEN-LAST:event_pnlQuestionBankMouseReleased

    private void pnlResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlResultsMouseClicked

    private void pnlResultsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlResultsMouseEntered

    private void pnlResultsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlResultsMouseExited

    private void pnlResultsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultsMousePressed
        // TODO add your handling code here:
        pnlResults.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlResultsMousePressed

    private void pnlResultsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultsMouseReleased
        // TODO add your handling code here:
        pnlResults.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlResultsMouseReleased

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        LecturerResultDashBoard lecturerResultDashBoard = new LecturerResultDashBoard();        
        lecturerResultDashBoard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        ExamDetails examDetails = new ExamDetails();
        examDetails.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        ExamLink examLink = new ExamLink();
        examLink.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        ExamSession examSession = new ExamSession();
        examSession.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        ExamQuestion examQuestion = new ExamQuestion();
        examQuestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Answers answers = new Answers();
        answers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerExamDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerExamDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerExamDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerExamDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerExamDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblBack;
    private javax.swing.JPanel pnlAnswerScheme;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlExamDetails;
    private javax.swing.JPanel pnlExamLink;
    private javax.swing.JPanel pnlExamSession;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlQuestionBank;
    private javax.swing.JPanel pnlResults;
    // End of variables declaration//GEN-END:variables
}
