/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csse.exam.main;

import com.csse.exam.service.ModuleService;
import java.awt.Color;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author saranki
 */
public class LecturerSearchCourse extends javax.swing.JFrame {

    private final ModuleService moduleService = new ModuleService();
    public static String moduleCode;
    /**
     * Creates new form LecturerSearchCourse
     */
    public LecturerSearchCourse() {
        initComponents();
        loadModulesToList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavigation = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlCourse = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        pnlExam = new javax.swing.JPanel();
        lblExam = new javax.swing.JLabel();
        pnlResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSystem = new javax.swing.JPanel();
        lblSystem = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlSearchCourse = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstModules = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modules");
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavigation.setBackground(new java.awt.Color(105, 135, 170));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashboard.setBackground(new java.awt.Color(70, 102, 144));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlDashboardMouseReleased(evt);
            }
        });

        lblDashboard.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("Dashboard");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 50));

        pnlCourse.setBackground(new java.awt.Color(70, 102, 144));
        pnlCourse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCourseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlCourseMouseReleased(evt);
            }
        });

        lblCourse.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setText("Course");
        lblCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlCourseLayout = new javax.swing.GroupLayout(pnlCourse);
        pnlCourse.setLayout(pnlCourseLayout);
        pnlCourseLayout.setHorizontalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCourseLayout.setVerticalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 50));

        pnlExam.setBackground(new java.awt.Color(70, 102, 144));
        pnlExam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlExam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlExamMouseReleased(evt);
            }
        });

        lblExam.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblExam.setForeground(new java.awt.Color(255, 255, 255));
        lblExam.setText("Exam");

        javax.swing.GroupLayout pnlExamLayout = new javax.swing.GroupLayout(pnlExam);
        pnlExam.setLayout(pnlExamLayout);
        pnlExamLayout.setHorizontalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlExamLayout.setVerticalGroup(
            pnlExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExam, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 130, 50));

        pnlResult.setBackground(new java.awt.Color(70, 102, 144));
        pnlResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlResultMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlResultMouseReleased(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, 50));

        pnlLogo.setBackground(new java.awt.Color(204, 217, 233));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csse/exam/resource/SLIIT_Crest.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNavigation.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 100));

        getContentPane().add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 620));

        pnlSystem.setBackground(new java.awt.Color(105, 135, 170));
        pnlSystem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSystem.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSystem.setText("MCQ EXAM SYSTEM");
        pnlSystem.add(lblSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("BobTheBuilder");
        lblUser.setToolTipText("");
        pnlSystem.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 10, 460, 20));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(204, 217, 233));
        lblLogout.setText("(LOGOUT)");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSystem.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, 20));

        pnlTitle.setBackground(new java.awt.Color(70, 102, 144));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Modules");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSystem.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, 40));

        getContentPane().add(pnlSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 830, 100));

        pnlContent.setBackground(new java.awt.Color(204, 217, 233));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSearchCourse.setBackground(new java.awt.Color(204, 217, 233));
        pnlSearchCourse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlSearchCourse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lstModules.setBackground(new java.awt.Color(204, 217, 233));
        lstModules.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lstModules.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lstModules.setFixedCellHeight(50);
        lstModules.setSelectionBackground(new java.awt.Color(70, 102, 144));
        lstModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstModulesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstModules);

        pnlSearchCourse.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 450));

        pnlContent.add(pnlSearchCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 770, 450));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 830, 520));

        setSize(new java.awt.Dimension(966, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDashboardMouseClicked

    private void pnlDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseEntered
        // TODO add your handling code here:
        //        jPanel5.setBackground(new Color(153,150,255));
    }//GEN-LAST:event_pnlDashboardMouseEntered

    private void pnlDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseExited
        // TODO add your handling code here:[153,204,255]
    }//GEN-LAST:event_pnlDashboardMouseExited

    private void pnlDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMousePressed
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlDashboardMousePressed

    private void pnlDashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDashboardMouseReleased
        // TODO add your handling code here:
        pnlDashboard.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlDashboardMouseReleased

    private void pnlCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMousePressed
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlCourseMousePressed

    private void pnlCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCourseMouseReleased
        // TODO add your handling code here:
        pnlCourse.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlCourseMouseReleased

    private void pnlExamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMousePressed
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlExamMousePressed

    private void pnlExamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExamMouseReleased
        // TODO add your handling code here:
        pnlExam.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlExamMouseReleased

    private void pnlResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMousePressed
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(204, 217, 233));
    }//GEN-LAST:event_pnlResultMousePressed

    private void pnlResultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlResultMouseReleased
        // TODO add your handling code here:
        pnlResult.setBackground(new Color(70, 102, 144));
    }//GEN-LAST:event_pnlResultMouseReleased

    private void lstModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstModulesMouseClicked
        // TODO add your handling code here:
        //click and send the moduleid
        moduleCode = lstModules.getSelectedValue().split("   →   ")[0];
        LecturerExamDashboard lecturerExamdashboard = new LecturerExamDashboard();
        lecturerExamdashboard.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lstModulesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerSearchCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerSearchCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerSearchCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerSearchCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerSearchCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblExam;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSystem;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> lstModules;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlCourse;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlExam;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlSearchCourse;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables

    private void loadModulesToList() {
        Map<String, String> allModules = moduleService.getAllModules();
        DefaultListModel defaultListModel = new DefaultListModel();
        for (Map.Entry<String, String> modules : allModules.entrySet()) {
            defaultListModel.addElement(modules.getKey() + "   →   " + modules.getValue());
            
            lstModules.setModel(defaultListModel);
        }
    }
}
